### ISSUE TITLE
Can't create a Saferoom, and other lies I can tell myself because I'm stupid

### ISSUE THREAD

**Issue by Onethinboi** [TheCallunxz/Left2Mine#15]
Basically , my main concern is how do I create Saferooms, because just placing a Saferoom node, building a room around it, and placing two safroom doors on the opposite sides, doesn't work, If somebody could explain this I would appreciate. 
Also, not much of a grippe, but can I spawn in special infected with a node on their own?

Just asking.
But the saferoom is genuienly needed sooooooooooo...

**Comment by TheCallunxz** [comment]
Lol I love the title. 

You have to place the saferoom node down and then place the saferoom door for the entrance then for the exit. Make sure it's that order. Also make sure you're not placing fake saferoom doors.

Individual spawners are possible in the future but the AI director decides what to spawn so it's not guaranteed. You can always force a spawn using the director command along with a command block.
